/**
 * Represents information about a brand.
 * @typedef {Object} BRAND
 * @property {string} logo - The URL or path to the brand's logo.
 * @property {string} name - The name of the brand.
 * @property {number} visitors - The number of visitors associated with the brand.
 * @property {string} revenues - The revenue generated by the brand.
 * @property {number} sales - The number of sales associated with the brand.
 * @property {number} conversion - The conversion rate of the brand.
 */
export type BRAND = {
  logo: string;
  name: string;
  visitors: number;
  revenues: string;
  sales: number;
  conversion: number;
};
